### Requisição GET para obter o histórico
GET http://127.0.0.1:5000/historico
Content-Type: application/json

### Requisição POST para somar dois números
POST http://127.0.0.1:5000/soma
Content-Type: application/json

{
  "Numero 1:": 5,
  "Numero 2:": 10
}

### Requisição DELETE para apagar um item do histórico pelo ID
DELETE http://127.0.0.1:5000/historico/0 # mudar para cada id desejado
Content-Type: application/json
